enum AppStrings {
    static let fullTime = "FT"
    static let halfTime = "HT"
    static let notStarted = "-"
    static let inProgressPlaceholder = "36'"
    static let icPointerRight = "ic_pointer_right"
    static let football = "Football"
    static let basketball = "Basketball"
    static let americanFootball = "Am. Football"
    static let appTitle = "Sofascore"
    static let settings = "Settings"
    static let fullTimeDetail = "Full Time"
    static let halfTimeDetail = "Half Time"
    static let icTitle = "ic_title"
    static let icTrophy = "ic_trophy"
    static let icSettings = "ic_settings"
    static let icArrowLeft = "ic_arrow_left"
    static let dash = "-"
}
