enum AppStrings {
    static let fullTime = "FT"
    static let halfTime = "HT"
    static let notStarted = "-"
    static let inProgressPlaceholder = "36'"
    static let icPointerRight = "ic_pointer_right"
    static let football = "Football"
    static let basketball = "Basketball"
    static let americanFootball = "Am. Football"
    static let appTitle = "Sofascore"
    static let settings = "Settings"
    static let fullTimeDetail = "Full Time"
    static let halfTimeDetail = "Half Time"
    static let icTitle = "sofascore_title"
    static let icTrophy = "ic_trophy"
    static let icSettings = "ic_settings"
    static let icArrowLeft = "ic_arrow_left"
    static let icFootball = "ic_football"
    static let icBasketball = "ic_basketball"
    static let icAmericanFootball = "ic_american_football"
    static let scoreDash = "-"
    static let titleSeparator = " · "
    static let footballSlug = "football"
    static let basketballSlug = "basketball"
    static let americanFootballSlug = "am-football"
    static let errorTitle = "Error"
    static let errorMessage = "Could not load matches. Check your connection and try again."
    static let ok = "OK"
    static let usernamePlaceholder = "Username"
    static let passwordPlaceholder = "Password"
    static let loginButton = "Log in"
    static let logoutButton = "Log out"
    static let loginFailed = "Login failed. Check your credentials."
    static let loginEmptyFields = "Please enter username and password."
    static let loggedInAs = "Logged in as"
    static let eventsCount = "Events in DB"
    static let leaguesCount = "Leagues in DB"
    static let matchesTab = "Matches"
    static let standingsTab = "Standings"
    static let detailsTab = "Details"
    static let playersTab = "Players"
    static let teamInfo = "Team Info"
    static let totalPlayers = "Total Players"
    static let tournaments = "Tournaments"
    static let venue = "Venue"
    static let stadium = "Stadium"
    static let coachPrefix = "Coach: "
    static let noIncidents = "No results yet."
    static let viewTournamentDetails = "View Tournament Details"
    static let incidentsLoadError = "Could not load incidents."
    static let foul = "Foul"
    static let positionColumn = "#"
    static let teamColumn = "Team"
    static let columnPlayed = "P"
    static let columnWins = "W"
    static let columnDraws = "D"
    static let columnLosses = "L"
    static let columnGoals = "Goals"
    static let columnPoints = "PTS"
    static let columnDiff = "DIFF"
    static let columnPercentage = "PCT"
    static let firstHalf = "First Half"
    static let secondHalf = "Second Half"
    
    static let icIncidentYellowCard = "ic_incident_yellow_card"
    static let icIncidentRedCard = "ic_incident_red_card"
    static let icIncidentGoalFootball = "ic_incident_goal_football"
    static let icIncidentBasketball1 = "ic_incident_basketball_1"
    static let icIncidentBasketball2 = "ic_incident_basketball_2"
    static let icIncidentBasketball3 = "ic_incident_basketball_3"
    static let icIncidentAmfFieldGoal = "ic_incident_amf_field_goal"
    static let icIncidentAmfTouchdown = "ic_incident_amf_touchdown"
    static let icIncidentAmfExtraPoint = "ic_incident_amf_extra_point"
    static let icIncidentAmfTwoPoint = "ic_incident_amf_two_point"
    
    static let icProfileSymbol = "person.crop.circle.fill"
    static let icCloseSymbol = "xmark"

    static func quarter(_ number: Int) -> String { "Q\(number)" }
    
    static func round(_ number: Int) -> String { "Round \(number)" }
    
    // MARK: - Team of the Season
    static let totsTitle = "Team of the Season"
    static let totsMockBadge = "Mock preview · no real data"
    static let totsClearAll = "Clear all"
    static let totsSubmit = "Submit"
    static let totsRemove = "Remove"
    static let lineGoalkeepers = "Goalkeepers"
    static let lineDefenders = "Defenders"
    static let lineMidfielders = "Midfielders"
    static let lineAttackers = "Attackers"
    static let totsCommunityXI = "Community XI"
    static let totsBackToMyTeam = "Back to my team"
    static let totsVotesLine = "128,402 votes"
    static let totsDaysLeft = "2 days left to vote"
    static let totsTrophySymbol = "trophy.fill"
    static let totsBackToHome = "Back to home screen"
    static let totsShareIntro = "My Community Team of the Season"

    static func totsSelected(_ count: Int) -> String { "\(count) / 11 selected" }
    static func totsRemoved(_ count: Int) -> String { "\(count) removed to fit the new formation" }
    }

